spring.datasource.url=  jdbc:postgresql://ep-young-dew-az9747ja-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yaKDX3RnZx4G@ep

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false